domain: bigbang.dev

registryCredentials:
  registry: "###ZARF_REGISTRY###"
  username: "zarf-pull"
  password: "###ZARF_REGISTRY_AUTH_PULL###"

networkPolicies:
  enabled: false
jaeger:
  enabled: false
kiali:
  enabled: false
clusterAuditor:
  enabled: false
gatekeeper:
  enabled: false
logging:
  enabled: false
eckoperator:
  enabled: false
fluentbit:
  enabled: false
monitoring:
  enabled: false
twistlock:
  enabled: false